### PR TITLE
Contributing Document

### PR DESCRIPTION
**Pull request by TangoYankee**
## Checklist
 - [X] Created clear and concise name
 - [X] Focused on one issue
 - [x] Achieved 7/10 lint score on changed files
 - [X] Referenced issue number and title
 - [X] Described implementation/solution
 - [x] Asked for pull request review

## Issue:
 - Number: #9
 - Title: Contributing

## Implementation/Solution
Create contributing document to on-board new users

### CODE REVIEW

**Review by Golden-Boy — APPROVED** [review]
Everything was easy to follow and straighforward in Ubuntu. I'm going to have to look over how to get it to work with Arch Linux.

**Review by Golden-Boy — COMMENTED** [review]
Everything worked as intended for Ubuntu. As a reminder, under the 'Software' category, Flask needed to be added as a software.

**Comment by TangoYankee** [comment]
@Golden-Boy If you're okay with this version, could you approve the changes?
1. Select the *files changed* tab
2. Click the green *review changes*
3. Choose the *approve* radio option
4. *Submit Review*

Otherwise, the merging remains blocked.

**Review by Golden-Boy — APPROVED** [review]

**Comment by Golden-Boy** [comment]
@TangoYankee I just did it. If there are any issues please let know and I'll try it again.

**Review by Golden-Boy — APPROVED** [review]

**Pull request merged**
